---
title: Managed Kaos
email: info@managedkaos.com
description: >-
  Everything's under control.
baseurl: ""
url: "https://managedkaos.com"
twitter_username: managedkaos
github_username: managedkaos

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  portfolio:
    output: true

include:
  - _pages

defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      permalink: /:basename/
